name: roigbiv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=2.0
  - scipy
  - pandas
  - tifffile
  - scikit-image
  - matplotlib
  - pyyaml
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch
    - torchvision
    - suite2p
    - "cellpose<4.0.0"
    - streamlit
    - ipywidgets
    - "napari[all]>=0.4.19"
    - -e .
